Allow confirm with no choice
mitsuhiko/dialoguer pull request #101
Opened 2021-01-22 18:03 UTC by spenserblack

Adds `Confirm::interact_opt` and `Confirm::interact_on_opt` to handle situations where the user
wishes to answer neither "yes" nor "no".

Resolves #100

2021-01-23 13:22 UTC, pksunkara requested changes

2021-01-23 13:22 UTC, pksunkara commented on src/theme.rs
> +            None => {
This needs more thought.

2021-01-23 13:22 UTC, pksunkara commented on src/prompts/confirm.rs
> +                    Key::Escape | Key::Char('q') => {
You need `if allow_quit` here to check.

2021-01-23 13:22 UTC, pksunkara commented on src/prompts/confirm.rs
> +                            rv = Some(val);
I am not sure about this line. Did you check that the previous behavior remains the same?

2021-01-23 19:47 UTC, spenserblack commented on src/prompts/confirm.rs
> +                            rv = Some(val);
I'll push up a commit soon that changes this behavior slightly. After some thought, I think that, if waiting for newline, <kbd>Esc</kbd> or <kbd>q</kbd> should clear the selection, but continue waiting for newline.

2021-01-23 19:57 UTC, spenserblack commented on src/theme.rs
> +            None => {
Is the problem the coding style or the behavior?

The behavior makes sense to me -- if there is no prompt and no answer, there is nothing to write to screen. Otherwise, write only the prompt. Should a placeholder like `"?"` or `"no answer"` be written to the screen?

2021-01-23 20:00 UTC, spenserblack commented on src/prompts/confirm.rs
> +                    Key::Escape | Key::Char('q') => {
Thank you for finding that! It was foolish of me to forget that :facepalm: :sweat_smile:

2021-01-23 20:15 UTC, spenserblack commented on src/prompts/confirm.rs
> +                            rv = Some(val);
I pushed up a commit that now writes `n/a` if the answer was neither `yes` nor `no`. After thinking about it a bit, it's much better :smiley:

Also, I was able to make the change much more readable than what I previously did :laughing:

2021-01-23 20:18 UTC, spenserblack commented on src/theme.rs
> +            None => {
I pushed up a commit that now writes `n/a` if the answer was neither `yes` nor `no`. After thinking about it a bit, I believe it's much better :smiley:

Also, I think my changes in this file are now much more readable than what I previously did :laughing:

2021-01-23 20:20 UTC, spenserblack commented
@pksunkara Thank you for your feedback! I pushed up some commits that address your comments.

2021-01-30 14:42 UTC, pksunkara requested changes
I am still not sold on the `n/a` being shown. Is there any prior work in other languages/programs we can look at? How about `cancel`?

2021-01-30 14:42 UTC, pksunkara commented on examples/confirm.rs
> +        .unwrap()
In this example, when pressing `q` after prompt show (without pressing `Enter` yet) should show `n/a`. It shows `yes` or `no` when `y` or `n` is pressed.

2021-01-30 18:27 UTC, spenserblack commented on examples/confirm.rs
> +        .unwrap()
Just to confirm what it should look like. Is this what you're envisioning for `interact_opt` with `wait_for_newline(true)`?

###### Prompt displayed, no user input
```
? Do you really really really really really want to continue? (y/n) ›
```


###### User presses `Esc` or `q`
```
? Do you really really really really really want to continue? (y/n) › n/a
```

###### User presses `Enter` after `Esc` or `q`
```
? Do you really really really really really want to continue? (y/n) › cancel
```

2021-01-30 22:15 UTC, pksunkara commented on examples/confirm.rs
> +        .unwrap()
yeah, but `cancel` instead of `n/a` in second scenario too.

2021-01-31 00:04 UTC, spenserblack commented on examples/confirm.rs
> +        .unwrap()
Got it. That makes sense to me for the first and third scenarios (I chose `n/a` to limit to 3 characters, but I have no strong opinion on what it should be), but I have a question about the second scenario.

***

What would this mean for the `default` method?

Currently, there are 3 states for a confirm prompt:
- nothing (no input ***or*** `q` or `Esc` input)
- `no` (`n` input)
- `yes` (`y` input)

and `default` lets you set the initial state to either `Yes` or `No`.

If `cancel` is displayed when `Esc` or `q` are pressed, then there are 4 states:
- nothing (no input)
- `no` (`n` input)
- `yes` (`y` input)
- `cancel` (`q` or `Esc` input)

`default` is used to set the initial state. Currently it takes a `bool`, so the initial state can be either `yes` or `no`. If `cancel` is a state that can be displayed before pressing `Enter`, then I don't think `default` taking a `bool` would be sufficient. In my opinion, it would then need to take either an `Option<bool>` or an enum with `No`, `Yes`, and `Cancel` variants. This would be a breaking change.

If `q` and `Esc` reverts to the "nothing" state, then I think a user not calling `default` before `interact_opt` can be assumed to mean that they want *no value* to be the default value. But if `cancel` is displayed in the second scenario, and `default` continues to take a `bool`, then what would the user not calling `default` mean? Would it mean they want *no default value*, or that the default value is `cancel`?

2021-01-31 00:25 UTC, spenserblack commented
# Note to self

Found that, when default is set in an optional confirm that waits for newline, cancel is ignored -- if initial state is `yes`, `Esc` is pressed, then `Enter`, the final value will be `Some(true)`, not `None`.

2021-01-31 16:55 UTC, pksunkara commented on examples/confirm.rs
> +        .unwrap()
What about removing `cancel` and `n/a` and just not displaying anything for `None` state?

2021-02-01 15:12 UTC, spenserblack commented on examples/confirm.rs
> +        .unwrap()
>just not displaying anything for `None` state?

Isn't that the current behavior as the PR currently is?

2021-02-01 18:40 UTC, pksunkara commented on examples/confirm.rs
> +        .unwrap()
After giving it some thought, let's remove `cancel` from the end too. Basically no `cancel` or `n/a` ever.

2021-02-02 14:07 UTC, spenserblack commented on examples/confirm.rs
> +        .unwrap()
Done

2021-02-02 22:09 UTC, merged