Feature: Add fuzzy single select prompt
mitsuhiko/dialoguer pull request #124
Opened 2021-08-09 11:18 UTC by deg0nz

This superseeds #79.

I added all the changes that where requested by @pksunkara in #79.

I added a cursor simulation, so we have a basic functionality to change the search term conveniently. Currently, the cursor is fixed to be black font on white background, but I'd like this thing to be possible to be styled by the user. 

Here's how it currently looks:

![fuzzy_cursor](https://user-images.githubusercontent.com/6370295/128697470-8a623c10-44fd-4032-833c-8c325ce52956.gif)

This PR is to be discussed (maybe I forgot something).

**This stuff is still to be done until I consider this PR "ready to merge":**

- [ ] Make cursor styleable (or better: detect terminal colors and style it based on that)
- [ ] Remove/change old "paging code" and assume the fuzzy select narrows it down to 1 page (as commented by @pksunkara in #79)

2021-08-09 11:18 UTC, deg0nz commented
I would like to detect the current terminal colors and style the cursor based on that.

@pksunkara do you know, if this is possible to find out via the `console` crate?

2021-08-11 15:53 UTC, pksunkara requested changes

2021-08-11 15:53 UTC, pksunkara commented on src/lib.rs
>  #[cfg(feature = "editor")]
This is for `mod edit` IIRC.

2021-08-11 15:53 UTC, pksunkara commented on src/prompts/fuzzy_select.rs
> +        Select::with_theme(&SimpleTheme)
`Select`?

2021-08-11 15:53 UTC, pksunkara commented on src/theme.rs
> +            )?;
You don't need this statement.

2021-08-11 15:53 UTC, pksunkara commented on src/theme.rs
> +            let st_cursor = style(search_term.to_string().chars().nth(cursor_pos).unwrap()).black().on_white();
No `style` here

2021-08-11 15:53 UTC, pksunkara commented on src/theme.rs
> +            let cursor = style(" ".to_string()).black().on_white();
No `style` here

2021-08-11 15:53 UTC, pksunkara commented on src/prompts/fuzzy_select.rs
> +                        term.flush()?
```suggestion
                        term.flush()?;

```

2021-08-11 15:53 UTC, pksunkara commented on src/prompts/fuzzy_select.rs
> +    fuzzy_search_is_case_sensitive: bool,
```suggestion
    ignore_casing: bool,
```

2021-08-11 19:40 UTC, deg0nz commented on src/prompts/fuzzy_select.rs
> +        Select::with_theme(&SimpleTheme)
Fixed. Don't know how that got in there 😅

2021-08-11 19:43 UTC, deg0nz commented on src/lib.rs
>  #[cfg(feature = "editor")]
Fixed.

2021-08-11 19:43 UTC, deg0nz commented on src/theme.rs
> +            )?;
Removed.

2021-08-11 19:44 UTC, deg0nz commented on src/prompts/fuzzy_select.rs
> +                        term.flush()?
Fixed.

2021-08-11 19:44 UTC, deg0nz commented on src/prompts/fuzzy_select.rs
> +    fuzzy_search_is_case_sensitive: bool,
Done.

2021-08-11 20:07 UTC, deg0nz commented
@pksunkara after your suggestion to change the `ignore_casing` variable, I stumbled upon the fact, that this variable changes nothing regarding the fuzzy searcher itself. It just adds the characters as lower-case to the search string.

I got nosy and looked into the code of the `fuzzy-matcher` code. The `Default` implementation of `SkimMatcherV2` already [uses "smart" case sensitive matching](https://github.com/lotabout/fuzzy-matcher/blob/ee73fa4559a9ea06e51b54b0a436590c911c18a1/src/skim.rs#L621) which gives penalty if the case is not matched and bonus if the case is matched.

I suggest, **we remove the whole case-sensitive thing**, since the `fuzzy-matcher` already handles that.

2021-08-11 20:08 UTC, pksunkara commented
Sounds good to me.

2021-08-11 20:13 UTC, pksunkara requested changes

2021-08-11 20:13 UTC, pksunkara commented on examples/fuzzyselect.rs
> +    let position = FuzzySelect::with_theme(&ColorfulTheme::default())
```suggestion
    let selection = FuzzySelect::with_theme(&ColorfulTheme::default())
```

2021-08-11 20:13 UTC, pksunkara commented on src/prompts/fuzzy_select.rs
> +    }
Let's remove paging completely for fuzzy select

2021-08-11 20:30 UTC, deg0nz commented on examples/fuzzyselect.rs
> +    let position = FuzzySelect::with_theme(&ColorfulTheme::default())
done

2021-08-11 20:41 UTC, pksunkara approved these changes

2021-08-11 20:42 UTC, merged

2022-05-08 18:19 UTC, Araxeus commented
@pksunkara why is there no documentation for this feature?

Did I somehow miss it?

2022-05-09 00:30 UTC, pksunkara commented
Release 0.10.1 which should have documentation about it.