Add support for optional history processing to `Input`
mitsuhiko/dialoguer pull request #126
Opened 2021-08-11 19:13 UTC by CraZySacX

* Added support for optional history processing to `Input`.  

Up/Down arrow keys are read in `interact_text_on` and allow for history to be read via a user supplied function.
History is written after successful input validation via the same user supplied function.

2021-08-11 20:33 UTC, pksunkara requested changes
Can you please add an example called `history.rs`?

2021-08-11 20:51 UTC, jasonozias commented
Will do.  And seems to have cause some build failures.  I'll look into those as well.

2021-08-11 20:52 UTC, pksunkara commented
While I would appreciate you fixing the failures, I think they are unrelated.

2021-08-11 20:54 UTC, pksunkara commented on src/prompts/input.rs
> +    history: Option<Box<dyn FnMut(usize, Option<&T>) -> Option<String> + 'a>>,
While I am okay with this, what do you think about a `History` struct that has `read` and `write` fns? And all of this should be gated behind `history` feature.

2021-08-11 21:20 UTC, jasonozias commented on src/prompts/input.rs
> +    history: Option<Box<dyn FnMut(usize, Option<&T>) -> Option<String> + 'a>>,
I initially had something like that setup, but consolidated down to one.   I can go that route again no problem.   And I'll add the gate as well.

2021-08-12 00:31 UTC, jasonozias commented
Went with a `History` trait and added the feature flags.

2021-08-12 00:36 UTC, pksunkara requested changes

2021-08-12 00:36 UTC, pksunkara commented on src/history.rs
> +        T: Clone + FromStr + Display;
Do you need `FromStr`?

2021-08-12 00:36 UTC, pksunkara commented on src/prompts/input.rs
> +    fn write_history(&mut self, _value: &T) {}
I don't think you need this functions. You can put the `cfg` on statements in the `_interact` itself.

2021-08-12 01:15 UTC, jasonozias commented on src/history.rs
> +        T: Clone + FromStr + Display;
Removed.

2021-08-12 01:15 UTC, jasonozias commented on src/prompts/input.rs
> +    fn write_history(&mut self, _value: &T) {}
Moved back to being gated inline.

2021-08-12 22:52 UTC, pksunkara approved these changes

2021-08-12 22:52 UTC, merged