Fix paging
mitsuhiko/dialoguer pull request #130
Opened 2021-08-29 21:12 UTC by deg0nz

This addresses #125 

The following things have been addressed:

* I extracted all the functions regarding the paging functionality into an own module.
* The module is able to update terminal information via an `update()` function. This allows the rendering to adjust to terminal resizing.
But since the `match term.read_key()?` seems to block the rendering loop, the healing will only be achieved after the next key press
* All prompts that are related to item lists (except `fuzzy-select` for now) are adjusted to use the new paging module.
    * The prompt rendering functions have an additional parameter to be able to print the paging information

Currently the whole thing behaves like this when the terminal is resized:

![fix_paging](https://user-images.githubusercontent.com/6370295/131265455-dbaa1ee6-6ab9-4c9c-be4c-b5415bf35f81.gif)

2021-09-01 11:48 UTC, pksunkara requested changes
Good progress. I want to see if we can improve the following:

1. Show pages after the prompt instead of before? or maybe something else?
2. Re render when term size changes instead of being blocked.

2021-09-01 11:48 UTC, pksunkara commented on examples/select.rs
> +        "Banana",
Make a different example called `paging.rs`

2021-09-01 11:48 UTC, pksunkara commented on src/lib.rs
> +pub use paging::Paging;
Why do we need to export it as part of lib?

2021-09-01 11:48 UTC, pksunkara commented on src/prompts/multi_select.rs
> +    pub fn paged(&mut self, _val: bool) -> &mut MultiSelect<'a> {
Let's delete the function directly, we dont need deprecation warnings.

2021-09-01 11:48 UTC, pksunkara commented on src/prompts/select.rs
> +    pub fn paged(&mut self, _val: bool) -> &mut Select<'a> {
Let's delete this.

2021-09-01 11:48 UTC, pksunkara commented on src/prompts/select.rs
> +        let mut paging = Paging::new(term, self.items.len());
Move this line above `render`.

2021-09-01 11:48 UTC, pksunkara commented on src/prompts/sort.rs
> +    pub fn paged(&mut self, _val: bool) -> &mut Sort<'a> {
Let's delete this.

2021-09-01 11:48 UTC, pksunkara commented on src/prompts/sort.rs
> +        let mut paging = Paging::new(term, self.items.len());
Move this above `render`

2021-09-01 11:48 UTC, pksunkara commented on src/theme.rs
> +    fn format_select_prompt_paged(
Unusued function. Let's delete this.

2021-09-01 11:48 UTC, pksunkara commented on src/paging.rs
> +    }
The above 4 functions can be just direct member access by making members `pub`. Let's delete them.

2021-09-01 11:48 UTC, pksunkara commented on src/paging.rs
> +            current_term_size: term.size(),
Let's cache `term.size()` into a var in this function instead of calling it twice.

2021-09-01 11:48 UTC, pksunkara commented on src/paging.rs
> +            self.current_term_size = self.term.size();
Let's cache `term.size()` into a var in this function instead of calling it twice.

2021-09-01 11:48 UTC, pksunkara commented on src/paging.rs
> +            render_prompt(paging_info)?;
```suggestion
            render_prompt(None)?;
```

We don't need to declare `paging_info` at the beginning of this function.

2021-09-01 11:48 UTC, pksunkara commented on src/paging.rs
> +    pub fn render_prompt<F: FnMut(Option<(usize, usize)>) -> io::Result<()>>(
Let's put `F: ...` in `where` instead of here.

2021-09-01 17:45 UTC, deg0nz commented on examples/select.rs
> +        "Banana",
Done

I'll comment all your comment with "Done" to make sure, I didn't forget anything

2021-09-01 17:45 UTC, deg0nz commented on src/lib.rs
> +pub use paging::Paging;
We don't need this. Just a typo.

Done

2021-09-01 17:45 UTC, deg0nz commented on src/prompts/multi_select.rs
> +    pub fn paged(&mut self, _val: bool) -> &mut MultiSelect<'a> {
done

2021-09-01 17:46 UTC, deg0nz commented on src/prompts/select.rs
> +    pub fn paged(&mut self, _val: bool) -> &mut Select<'a> {
Done

2021-09-01 17:46 UTC, deg0nz commented on src/prompts/select.rs
> +        let mut paging = Paging::new(term, self.items.len());
Done

2021-09-01 17:46 UTC, deg0nz commented on src/prompts/sort.rs
> +    pub fn paged(&mut self, _val: bool) -> &mut Sort<'a> {
Done

2021-09-01 17:46 UTC, deg0nz commented on src/prompts/sort.rs
> +        let mut paging = Paging::new(term, self.items.len());
Done

2021-09-01 17:46 UTC, deg0nz commented on src/theme.rs
> +    fn format_select_prompt_paged(
Done

2021-09-01 17:46 UTC, deg0nz commented on src/paging.rs
> +            current_term_size: term.size(),
Done

2021-09-01 17:46 UTC, deg0nz commented on src/paging.rs
> +            self.current_term_size = self.term.size();
Done

2021-09-01 17:46 UTC, deg0nz commented on src/paging.rs
> +            render_prompt(paging_info)?;
Done

2021-09-01 17:46 UTC, deg0nz commented on src/paging.rs
> +    pub fn render_prompt<F: FnMut(Option<(usize, usize)>) -> io::Result<()>>(
Done

2021-09-01 17:49 UTC, deg0nz commented on src/paging.rs
> +    }
Done

2021-09-01 17:52 UTC, deg0nz commented
I applied all your review suggestions.

I will look into dynamic resizing and position of paging information and ping you, when I have progress.

2021-09-03 08:48 UTC, deg0nz commented
Ok, I changed the prompt so that the paging info right to the prompt as in my inital example in #125.

**I gave the "automatic re-rendering on terminal resize" thing some thought:**

Since the `interact_on()`'s `loop`is blocked by the `match term.read_key()`, there is no real chance to check for the terminal size change without having an extra busy loop that observes the values of `term.size()`. 
I thought about adding an observer to `console::Term`, but `console` itself just uses the `terminal_size` crate which is polling the information from the OS. Since there is no real setter for the terminal size inside `Term`, we cannot add an observer for setting the value.

So here's an idea:

We implement an (optional) setting, where a new thread is spawned that permanently loops over `term.size()` and raises an event, if the value has changed. This event is then received by `interact_on` and a re-rendering of the output is triggered.

Possible caveats:

I seems that `terminal_size` gets the terminal size from `STDOUT`'s file descriptor on unix. I don't know how much load a busy `loop` on such a file descriptor would create. We could just try it out and see what happens...

We could also ask the `terminal_size` maintainers if they have an idea, how one could implement an observer over these values.

/ping @pksunkara

2021-09-04 09:10 UTC, pksunkara commented
Looks good. Linting job is failing.

> We could also ask the terminal_size maintainers if they have an idea, how one could implement an observer over these values.

I would appreciate if you can follow up on that and we can look to improve this feature in the future. But for now, I will merge this as soon as linting is fixed.

2021-09-05 19:09 UTC, deg0nz commented
Linting is fixed.

> I would appreciate if you can follow up on that and we can look to improve this feature in the future.

Will do.

2021-09-05 20:14 UTC, merged