Enable customization of number of rows for FuzzySelect
mitsuhiko/dialoguer pull request #214
Opened 2022-08-24 05:24 UTC by firebolt55439

Hi!

In this PR, I've made a small but useful extension to `FuzzySelect` that enables the user to decide how many options will be displayed at one time, rather than the default of the terminal height minus 2.

Example code:
```rust
FuzzySelect::with_theme(&ColorfulTheme::default())
                .with_prompt("What is your guess?")
                .with_visible_term_rows(5_usize)
                .items(word_slice)
                .report(true)
                .default(0)
                .interact()?;
```

Here's an example of how it looks with `visible_term_rows = 5`:

<img width="321" alt="image" src="https://user-images.githubusercontent.com/1293223/186335654-671660ec-8806-4219-807e-d179280efe8c.png">

I'm still somewhat new to Rust, let me know if there's any code style that can be improved.

2022-08-24 08:17 UTC, pksunkara commented on src/prompts/fuzzy_select.rs
> +        let visible_term_rows = self.visible_term_rows.unwrap_or(visible_term_rows);
Let's do a min here.

2022-08-24 22:07 UTC, firebolt55439 commented on src/prompts/fuzzy_select.rs
> +        let visible_term_rows = self.visible_term_rows.unwrap_or(visible_term_rows);
Fixed.

2022-08-29 20:42 UTC, firebolt55439 commented
@pksunkara I've addressed your feedback, mind giving this another glance?

2022-08-29 20:58 UTC, pksunkara requested changes
Sorry for the extra roundtrip, I should have commented on this earlier.

2022-08-29 20:58 UTC, pksunkara commented on src/prompts/fuzzy_select.rs
> +    /// Sets the number of visible options.
```suggestion
    /// Sets the maximum number of visible options.
```

2022-08-29 20:58 UTC, pksunkara commented on src/prompts/fuzzy_select.rs
> +    pub fn with_visible_term_rows(&mut self, rows: usize) -> &mut Self {
Let's name the fn and the member as `max_length` to be consistent.

2022-08-30 06:59 UTC, firebolt55439 commented on src/prompts/fuzzy_select.rs
> +    pub fn with_visible_term_rows(&mut self, rows: usize) -> &mut Self {
Fixed.

2022-08-30 06:59 UTC, firebolt55439 commented
Updated according to your feedback @pksunkara .

2022-08-30 07:38 UTC, pksunkara approved these changes

2022-08-30 07:38 UTC, merged