feat(fuzzy): implement multi-fuzzy-selection
mitsuhiko/dialoguer pull request #215
Opened 2022-08-29 18:41 UTC by RobWalt

This commit includes a working example to showcase the feature.

Items are selected with spacebar and the selection is confirmed with enter.

---

Short background story:

I've been using the command line tool `glab` to work with my gitlab repos. There, some subcommands use a fuzzy-selection-search to select e.g. labels of issues. I found this feature very handy and wanted to use it for shell-scripts etc, but couldn't find a CLI tool or library that provides something like that. I hope you'll like it as much as I do!

To be fair, I have to mention, that the implementation of this feature has one flaw: You can't specifically search for some search term which includes spaces. But in practice that's almost never the case and in the few cases where you search terms with spaces, you can just skip them while typing in your search term and the fuzzy match algo will work great anyways.

I'm ready to make changes, if you request some.

2022-09-01 20:07 UTC, pksunkara requested changes
Also missing `format_multi_fuzzy_select_prompt_item` and `format_multi_fuzzy_select_prompt` in `ColorfulTheme`

2022-09-01 20:07 UTC, pksunkara commented on src/theme.rs
> +    fn format_fuzzy_multi_select_prompt_item(
```suggestion
    fn format_multi_fuzzy_select_prompt_item(
```

2022-09-01 20:07 UTC, pksunkara commented on src/theme.rs
> +    pub fn fuzzy_select_multi_prompt_item(
```suggestion
    pub fn multi_fuzzy_select_prompt_item(
```

2022-09-01 20:07 UTC, pksunkara commented on src/prompts/multi_fuzzy_select.rs
> +            render.fuzzy_select_prompt(self.prompt.as_str(), &search_term, position)?;
Multi select prompt

2022-09-01 20:07 UTC, pksunkara commented on src/prompts/multi_fuzzy_select.rs
> +    /// Like `interact` but allows a specific terminal to be set.
No doc for this since it's not `pub`.

Please fix mistake in `fuzzy_select.rs` too.

2022-09-01 20:07 UTC, pksunkara commented on src/prompts/multi_fuzzy_select.rs
> +    /// Result contains `Some(index)` if user hit 'Enter' or `None` if user cancelled with 'Esc' or 'q'.
Above 2 statements need to be updated.

2022-09-01 20:07 UTC, pksunkara commented on src/prompts/multi_fuzzy_select.rs
> +    /// Like `interact` but allows a specific terminal to be set.
`interact_opt`

Would appreciate if you can fix this mistake in `fuzzy_select.rs` too.

2022-09-02 06:53 UTC, RobWalt commented on src/prompts/multi_fuzzy_select.rs
> +            render.fuzzy_select_prompt(self.prompt.as_str(), &search_term, position)?;
I think this can stay maybe? It only renders the line that shows the current fuzzy search term (if I'm not mistaken) and this isn't really different in the multi-fuzzy prompt.

I could still copy the functionality to separate concerns. What do you think here?

2022-09-02 07:18 UTC, RobWalt commented on src/prompts/multi_fuzzy_select.rs
> +            render.fuzzy_select_prompt(self.prompt.as_str(), &search_term, position)?;
I just added it for now together with the missing functions on `ColorfulTheme`.

2022-09-02 08:32 UTC, RobWalt commented
Fixed everything so far, thanks for the fast an thorough review 👍🏼

2022-10-20 10:41 UTC, closed without merging