feat: add fuzzy single select prompt
mitsuhiko/dialoguer pull request #79
Opened 2020-08-26 16:58 UTC by SirWindfield

Superseeds #34.

There is sadly one problem that I can't resolve. I wanted to add the search term to the prompt so that users can see what they typed. But I can't find a way to delete the old prompt. My attempt is commented out inside the loop.

When commenting out, I still get a new prompt each time I type a character.
Follow-up with a working GIF.

2020-08-26 17:19 UTC, SirWindfield commented
In the example I type `ice`. Since `Ice` matches exactly, it is shown first. 
![fuzzy](https://user-images.githubusercontent.com/5113257/91335701-0e297300-e7d1-11ea-9a1a-761bc8ccf0e9.gif)

2020-08-26 17:41 UTC, SirWindfield commented
Applying this patch does display the search prompt. As far as I understood, there is no performance impact. Preserve prompt does also delete all lines but keeps the prompt intact. Manually calling `clear` does delete the prompt as well.

```patch
diff --git a/src/prompts/fuzzy.rs b/src/prompts/fuzzy.rs
index 1e6859c..024460a 100644
--- a/src/prompts/fuzzy.rs
+++ b/src/prompts/fuzzy.rs
@@ -158,15 +158,11 @@ impl<'a> FuzzySelect<'a> {
         let matcher = fuzzy_matcher::skim::SkimMatcherV2::default();
 
         loop {
-            // TODO: resolve
-            // if !search_term.is_empty() {
-            //     render.clear_preserve_prompt(&size_vec)?;
-            //     match &self.prompt {
-            //         Some(prompt) => render.select_prompt(&format!("{}: {}", prompt, search_term))?,
-            //         None => render.select_prompt(&format!("> {}", search_term))?,
-            //     };
-            // }
-            // ENDTODO
+            render.clear()?;
+            match &self.prompt {
+                Some(prompt) => render.input_prompt_selection(prompt, &search_term)?,
+                None => render.select_prompt(&format!("> {}", search_term))?,
+            };
 
             // Maps all items to a tuple of item and its match score.
             let mut filtered_list = self.items.iter()
@@ -258,7 +254,6 @@ impl<'a> FuzzySelect<'a> {
             if filtered_list.len() > 0 && (sel < page * capacity || sel >= (page + 1) * capacity) {
                 page = sel / capacity;
             }
-            render.clear_preserve_prompt(&size_vec)?;
         }
     }
 }
\ No newline at end of file

```

2020-08-26 17:46 UTC, SirWindfield commented
I'll open another issue for this, but working on the code base the first time I had a hard time understanding some logic. Some parts have a rather high cognitive complexity and without comments they are hard to grasp. This should be opened as a new issue though.

Maybe some internal documentation would be nice as well. For example the render methods could include a short example on what the output looks like exactly. Ideally, `write_formatted_str` would actually return the string and not delegate the call to `self.term`. That way, the examples could be even run using `rustdoc` tests.

2020-08-27 10:32 UTC, SirWindfield commented
Fixed the prompt in the latest commit. Here are two screenshots, one with and one without a prompt text. The commit message does explain my changes to `Theme` to accomplish this:
![image](https://user-images.githubusercontent.com/5113257/91431936-57c19e80-e861-11ea-938f-d43d87497838.png)
![sc](https://user-images.githubusercontent.com/5113257/91431954-5e501600-e861-11ea-9c4e-cd302c6b2750.png)

2020-08-27 20:44 UTC, pksunkara requested changes

2020-08-27 20:44 UTC, pksunkara commented on Cargo.toml
> +fuzzy-matcher = "0.3.5"
Let's put this behind an optional feature flag.

2020-08-27 20:44 UTC, pksunkara commented on src/lib.rs
> +    confirm::Confirm, input::Input, fuzzy::FuzzySelect, multi_select::MultiSelect, password::Password, select::Select,
```suggestion
    confirm::Confirm, input::Input, fuzzy_select::FuzzySelect, multi_select::MultiSelect, password::Password, select::Select,
```

2020-08-27 20:44 UTC, pksunkara commented on src/prompts/mod.rs
> +pub mod fuzzy;
```suggestion
pub mod fuzzy_select;
```

2020-08-27 20:44 UTC, pksunkara commented on src/theme.rs
> +    fn format_fuzzy_prompt(
Please use the name `fuzzy_select` everywhere instead of just `fuzzy`.

2020-10-01 21:57 UTC, deg0nz commented
Hi, just a quick question about the return value of the `interact()` functions in this PR:
Is there a specific reason, why this here is returning a `String`? 
The other select-type prompts in dialoguer return `usize` as the position of the selected item(s) in the input array (`select`) or an array of the positions (`multi_select`) respectively. I was just starting to include the current state of this PR in my code and was expecting a `usize`, which confused me a little bit 😅 .

2020-10-03 12:14 UTC, kegesch commented
@deg0nz I was confused as well. Returning the index would coherent.
@SirWindfield If there are more items than free lines in the terminal, the line with the prompt and the search string is not displayed anymore and thus hard to see what was typed.

2020-10-03 12:18 UTC, pksunkara commented
The second issue is a general issue with dialoguer and need to be fixed in a more abstract way.

2020-10-18 21:33 UTC, pksunkara requested changes
Sorry, I wanted to fix the `Confirm` prompt first before looking at this which is why it took me quite a bit of time to review.

2020-10-18 21:33 UTC, pksunkara commented on src/prompts/fuzzy_select.rs
> +        self._interact_on(term, false)?.ok_or(io::Error::new(
`ok_or_else(|| io::Error`

2020-10-18 21:33 UTC, pksunkara commented on src/prompts/fuzzy_select.rs
> +        let pages = (self.items.len() / capacity) + 1;
`let pages = (self.items.len() as f64 / capacity as f64).ceil() as usize;`

2020-10-18 21:33 UTC, pksunkara commented on src/prompts/fuzzy_select.rs
> +    fn _interact_on(&self, term: &Term, allow_quit: bool) -> io::Result<Option<String>> {
Out should be `io::Result<Option<usize>>`

2020-10-18 21:33 UTC, pksunkara commented on src/prompts/fuzzy_select.rs
> +                .filter_map(|(item, score)| match score {
`|(item, score)| score.map(|s| (item, s))`

2020-10-18 21:33 UTC, pksunkara commented on src/prompts/fuzzy_select.rs
> +                render.select_prompt_item(item, idx == sel)?;
Please create a new `fuzzy_select_prompt_item` and corresponding functions in the theme

2020-10-18 21:33 UTC, pksunkara commented on src/prompts/fuzzy_select.rs
> +                            term.clear_last_lines(filtered_list.len())?;
`term.flush()?` needed here.

2020-10-18 21:33 UTC, pksunkara commented on src/prompts/fuzzy_select.rs
> +                Key::ArrowLeft => {
In `Input`, arrow left & right are used to move the cursor in the input which we need here to for the search term. We need to solve this issue.

2020-10-18 21:33 UTC, pksunkara commented on src/prompts/fuzzy_select.rs
> +                        render.input_prompt_selection(prompt, &filtered_list[sel].0)?;
Please create new `fuzzy_select_prompt_selection` and corresponding functions in theme.

2020-10-18 21:33 UTC, pksunkara commented on src/prompts/fuzzy_select.rs
> +
Need to move cursor to the prompt and flush here.

2020-10-18 21:33 UTC, pksunkara commented on src/prompts/fuzzy_select.rs
> +    lines_per_item: usize,
I don't think we need this. Ideally dialoguer should figure out the number of lines and intelligently do display them.

2020-10-18 21:33 UTC, pksunkara commented on src/prompts/fuzzy_select.rs
> +use std::ops::Rem;
Please merge the imports.

2021-01-31 15:47 UTC, ttys3 commented
what 's the status of this issue ? could it be merged to the master?

2021-04-06 17:19 UTC, ttys3 commented
`examples/fuzzyselect.rs` has dos file format, it should be unix.
`src/prompts/fuzzy_select.rs` has dos file format, it should be unix.

2021-04-06 17:24 UTC, SirWindfield commented
I will not continue to work on this PR. If someone wants to take over, feel free to do so!

2021-04-07 14:09 UTC, deg0nz commented
I would like to take over. I just don't know how to contribute to this particular PR. I've never taken over a PR before.

@SirWindfield can you assign it to me somehow? Or should I do something?

2021-04-07 14:12 UTC, pksunkara commented
You can make a new PR.

On Wed, Apr 7, 2021, 15:09 Beh ***@***.***> wrote:

> I would like to take over. I just don't know how to contribute to this
> particular PR. I've never taken over a PR before.
>
> @SirWindfield <https://github.com/SirWindfield> can you assign it to me
> somehow? Or should I do something?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/mitsuhiko/dialoguer/pull/79#issuecomment-814946201>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABKU37RDXBMIVUZBYYF2NTTHRRS5ANCNFSM4QMBO6QQ>
> .
>

2021-04-07 18:57 UTC, ttys3 commented
I think I could try to make a new PR. but currently my fork is just get this PR merged, I need to look into @pksunkara 's review message carefully and make some change to the code, and then make a new PR.

2021-06-23 21:45 UTC, deg0nz commented
Hey, @pksunkara 

I started to apply your suggestions in my fork and came pretty far. Could you please answer the questions I add to your comments above and explain some more stuff?

2021-06-23 21:46 UTC, deg0nz commented on src/prompts/fuzzy_select.rs
> +    /// Enables or disables paging
Where can I find an example for "real" paging?

2021-06-23 21:48 UTC, deg0nz commented on src/prompts/fuzzy_select.rs
> +                            term.clear_last_lines(filtered_list.len())?;
Should `term.clear_last_lines(filtered_list.len())?;` be replaced here, or should `term.flush()?` be added to the if clause? 

(I currently replaced it and it seems to work fine)

2021-06-23 21:51 UTC, pksunkara commented on src/prompts/fuzzy_select.rs
> +    /// Enables or disables paging
To test, make your terminal small in height and have more options than the number of lines. fzf would be a good example but not perfect.

2021-06-23 21:52 UTC, pksunkara commented on src/prompts/fuzzy_select.rs
> +                            term.clear_last_lines(filtered_list.len())?;
`flush` doesn't clear. We actually need to clear the last lines.

2021-06-24 18:49 UTC, deg0nz commented on src/prompts/fuzzy_select.rs
> +                Key::ArrowLeft => {
I have a question about this regarding the paging function:

Since we use the arrows left & right for navigating the cursor now, what should we do about the paging function? It is not navigable anymore (horizontally). 
Should we just assume, that the fuzzy search narrows the results down so we only need to navigate with the up & down keys?

2021-06-24 21:14 UTC, deg0nz commented on src/prompts/fuzzy_select.rs
> +                Key::ArrowLeft => {
I have an additional problem: 

Due to the fact, that we use an input combined with a select prompt, the terminal cursor is rendered at the bottom of the select prompt and not in the input prompt. (Of course, because there is the last character that was written to the terminal)

Do you have any idea, how I can render the cursor to the input prompt?

Here is a GIF of what I mean:
![fuzzy_cursor](https://user-images.githubusercontent.com/6370295/123332270-93d89500-d540-11eb-9ec6-e295b43a1be9.gif)

The only thing that comes to my mind is implementing a styleable "cursor" by myself that highlights the current position in the input string and add it to the rendering function.

2021-06-28 07:10 UTC, deg0nz commented on src/prompts/fuzzy_select.rs
> +                Key::ArrowLeft => {
Just in case you didn't get a notification, here's a ping @pksunkara :)

2021-06-30 11:25 UTC, pksunkara commented on src/prompts/fuzzy_select.rs
> +                Key::ArrowLeft => {
I think there are some terminal functions that allow you to move the cursor up and down lines. This has been a fundamental issue in the library for all prompts that I have been meaning to fix.

2021-06-30 11:26 UTC, pksunkara commented on src/prompts/fuzzy_select.rs
> +                Key::ArrowLeft => {
> Since we use the arrows left & right for navigating the cursor now, what should we do about the paging function? It is not navigable anymore (horizontally).

Not sure what to do. We need to fix the paging problem anyway when we have multiple pages of options for normal select prompt. But until then you can assume just one page since fuzzy narrows it down.

2021-08-11 20:43 UTC, closed without merging