Allow FnMut for validate
mitsuhiko/dialoguer pull request #96
Opened 2020-11-15 04:33 UTC by SOF3

This allows mutable closures for validation, allowing stateful
validators.

This breaks BC. Input::interact*() now take &mut self instead of &self.
However, this shall not break most usres,
since (I think) users usually use Input in chained syntax
or call one of the &mut methods (like with_prompt) separately,
which would require a `let mut` anyway.

2020-11-15 04:34 UTC, pksunkara commented
Can you please add an example?

2020-11-15 07:12 UTC, SOF3 commented
What example would you like? This just widens the type accepted by `validate_with`. It doesn't add any features.

2020-11-15 07:20 UTC, pksunkara commented
We do not have an example with validate in `examples` folder. Since you added the abitlity for stateful validators, I was asking you to please create an example with a stateful validator.

2020-11-15 15:03 UTC, SOF3 commented
I appended this to the existing validator example.

2020-11-15 19:18 UTC, pksunkara commented
Everything looks good. Can you please add an entry to changelog and I can merge this.

2020-11-16 02:46 UTC, SOF3 commented
Updated. Also bumped minor version since it's a BC break.

2020-11-16 04:28 UTC, pksunkara requested changes

2020-11-16 04:28 UTC, pksunkara commented on Cargo.toml
> +version = "0.8.0"
Can you revert this line? I will change it when releasing.

2020-11-16 04:51 UTC, pksunkara approved these changes

2020-11-16 05:44 UTC, merged